name: dhcp_server_prueba
role: dhcp_server
os_type: linux
vbox_ostype: Ubuntu_64
resources:
  cpus: 1
  memory_mb: 2048
  disk_gb: 10
storage:
  base_folder: M:/Servidores
network:
  adapter1:
    type: hostonly
    name: host-only
ip: 192.168.56.250
ansible_group: dhcp_servers
